#!/bin/bash


########################################
#            VARIABLES                 #
########################################


SERVER_DIR="/root/mc/"
BACKUP_DIR="/backup/"
MIN_RAM="256M"
MAX_RAM="1024M"



########################################
#            FUNCTIONS                 #
########################################

startServer() {
    cd $SERVER_DIR && screen -dmS mc java -Xmx$MAX_RAM -Xms$MIN_RAM -jar mc.jar
}

stopServer() {
    screen -S mc -X stuff "stop$(printf \\r)"
}

attachServer() {
    screen -r mc
}


getServerStatus() {
    if ! screen -list | grep -q "mc" 
    then
        echo false
    else
        echo true
    fi
}


backupServer() {
    TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
    ARCHIVE=$BACKUP_DIR$TIMESTAMP".zip"

    # Stop mc server
    stopServer

    # Sleep 5 seconds 
    sleep 5

    # Create backup
    zip -r  $ARCHIVE $SERVER_DIR

    # Start mc server
    startServer
}




########################################
#            MAIN FLOW                 #
########################################


if [ $1 = "start" ]
then
    # Only start server if it's not running already
    if [ $(getServerStatus) = true ]
    then
        echo "The server is already running!"
    else 
        startServer
    fi

elif [ $1 = "stop" ]
then
    stopServer


elif [ $1 = "backup" ]
then
    backupServer


elif [ $1 = "attach" ]
then
    attachServer


elif [ $1 = "status" ]
then
    # Call method to get the server status
    if [ $(getServerStatus) = true ]
    then
        echo "Server is running!"
    else
        echo "Server is not running!"
    fi
fi

